{% set name = "torchtnt" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchtnt-{{ version }}.tar.gz
    sha256: 0cff0fbb111cbfd808015c3e18bd8a8d9c8b4c2213eef0361f538db1eb85fcb8
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/requirements.txt
    sha256: 709c610f3287f0b6b84d08977ed7fe39eaf57336dd3f1ea3c93e15c225ece673
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/dev-requirements.txt
    sha256: cbc0e580c8868ad94db473d49552bd458446aefe64284bd4cc37d849a5a113e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - numpy
    - packaging
    - psutil
    - pyre-extensions
    - python >=3.7
    - setuptools
    - tensorboard
    - pytorch
    - tqdm
    - typing-extensions

test:
  imports:
    - torchtnt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/tnt
  summary: A lightweight library for PyTorch training tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
