{% set name = "torchtnt" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchtnt-{{ version }}.tar.gz
    sha256: 04630772762a2f2d0f5636cccf861ec833118beab66f1c5f5d156f6fb58ba51b
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/requirements.txt
    sha256: 709c610f3287f0b6b84d08977ed7fe39eaf57336dd3f1ea3c93e15c225ece673
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/dev-requirements.txt
    sha256: c728fba6d2aa5e0add8b43b14cbb0a48da2aa48f5df6f5edde175a71f0556858

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - numpy
    - packaging
    - psutil
    - pyre-extensions
    - python >=3.7
    - setuptools
    - tensorboard
    - pytorch
    - tqdm
    - typing-extensions

test:
  imports:
    - torchtnt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/tnt
  summary: A lightweight library for PyTorch training tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
